colorscheme distinguished

syntax on               " turn syntax highlighting on by default
filetype on             " detect type of file
filetype indent on      " load indent file for specific file type
filetype plugin on
autocmd FileType ruby,eruby set filetype=ruby.eruby.chef
autocmd FileType bash,bats set filetype=bash.bats

" common misspelled words
iabbrev teh the
iabbrev accross across
iabbrev ipry require 'pry' ; binding.pry

set laststatus=2
set statusline=%t[%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P

let g:gist_clip_command = 'pbcopy'
let g:gist_open_browser_after_post = 1
let g:gist_detect_filetype = 1
let g:gist_post_private = 1
let g:gist_browser_command = 'open %URL% &'

" my key mappings 
map <c-n> bn
map <Esc><Esc> :w<CR>
map <F10> :set paste<CR>
map <F11> :set nopaste<CR>
imap <F10> <C-O>:set paste<CR>
imap <F11> <nop>
set pastetoggle=<F11>

" undotree
nnoremap <F5> :UndotreeToggle<cr>

" <Ctrl-l> redraws the screen and removes any search highlighting.
nnoremap <silent> <C-l> :nohl<CR><C-l>

" spelling
" toggle spellchecking on and off with `\s`
nmap <silent> <leader>s :set spell!<CR>
" set region for dict
set spelllang=en_us
set spell

" Rubocop bindings
let g:vimrubocop_keymap = 0
nmap <Leader>r :RuboCop<CR>

noremap <Leader>W :w !sudo tee % > /dev/null

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set autoindent          " fix copying in with the stupid indendets
set autochdir           " so i don't have to keep traversing directories
set nocompatible        " use vim defaults
set scrolloff=3         " keep 3 lines when scrolling
set ai                  " set auto-indenting on for programming
set relativenumber

set showcmd             " display incomplete commands
set nobackup            " do not keep a backup file
set ruler               " show the current row and column

set hlsearch            " highlight searches
set incsearch           " do incremental searching
set showmatch           " jump to matches when entering regexp
set ignorecase          " ignore case when searching
set smartcase           " no ignorecase if Uppercase char present

set visualbell t_vb=    " turn off error beep/flash
set novisualbell        " turn off visual bell

set backspace=indent,eol,start  " make that backspace key work the way it should

" This is a bad habit, even in dvorak
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" Use CTRL-S for saving, also in Insert mode
noremap <C-S> :update<CR>
vnoremap <C-S> <C-C>:update<CR>
inoremap <C-S> <C-O>:update<CR>

set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows

highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%81v', 100)

autocmd vimenter * if !argc() | NERDTree | endif

execute pathogen#infect()
